# Generated by Django 5.2.4 on 2025-07-16 22:43
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(to='core.Autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='categorias',
            field=models.ManyToManyField(to='core.Categoria'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=200, db_index=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=100, db_index=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, db_index=True),
        ),
    ]
